### ISSUE TITLE
Unable to resolve version '2.4.13' for platform ''

### ISSUE THREAD

**Issue by jandubois** [SUSE/cf-buildpack-packager-docker#3]
While doing a code review for #2 I accidentally also tried to build an older Java buildpack, and it fails now:

```
$ docker run -it --rm -v $PWD:/out splatform/cf-buildpack-packager --accept-external-binaries SUSE java a839af1
+ '[' -z a839af1 ']'
+ git clone --recursive https://github.com/SUSE/cf-java-buildpack /cf-java-buildpack
...
+ git checkout a839af1
Note: checking out 'a839af1'.
...
+ bundle.ruby2.3 exec rake clean package OFFLINE=true PINNED=true
Pinning groovy version to
rake aborted!
Unable to resolve version '2.4.13' for platform ''
/cf-java-buildpack/rakelib/dependency_cache_task.rb:174:in `block in get_from_cache'
/cf-java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:57:in `block in cached'
/cf-java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:57:in `open'
/cf-java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:57:in `open'
/cf-java-buildpack/lib/java_buildpack/util/cache/cached_file.rb:57:in `cached'
/cf-java-buildpack/lib/java_buildpack/util/cache/download_cache.rb:80:in `get'
/cf-java-buildpack/rakelib/dependency_cache_task.rb:168:in `get_from_cache'
/cf-java-buildpack/rakelib/dependency_cache_task.rb:160:in `block (2 levels) in uris'
/cf-java-buildpack/rakelib/dependency_cache_task.rb:158:in `each'
/cf-java-buildpack/rakelib/dependency_cache_task.rb:158:in `block in uris'
/cf-java-buildpack/rakelib/dependency_cache_task.rb:157:in `each'
/cf-java-buildpack/rakelib/dependency_cache_task.rb:157:in `uris'
/cf-java-buildpack/rakelib/dependency_cache_task.rb:46:in `initialize'
/cf-java-buildpack/Rakefile:42:in `new'
/cf-java-buildpack/Rakefile:42:in `<top (required)>'
(See full trace by running task with --trace)
```

This used to work before; not sure what has changed.

**Comment by thardeck** [comment]
Is this still a use case because then we would need an older bundler and a newer in the docker image and need to distinguish?

```
+ bundle
Traceback (most recent call last):
        2: from /usr/bin/bundle:23:in `<main>'
        1: from /usr/lib64/ruby/2.5.0/rubygems.rb:303:in `activate_bin_path'
/usr/lib64/ruby/2.5.0/rubygems.rb:284:in `find_spec_for_exe': Could not find 'bundler' (1.16.1) required by your /cf-java-buildpack/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.16.1`
```
